本実装１
TUS-OSK/ranking-table pull request #12
Opened 2024-11-18 06:25 UTC by nekoyukichi

## Issue Number

- Close #6 

## Purpose

ゲームプレイデータを保存するため

## What's changed

 - DBのResults tableに保存し、201 Createdを返す

## Background / Compromises

 - 63行目をStatusCreatedで終わらせたら注意喚起の波線が出ていたのですが、何がダメかわからずStatusCreated,の後にgin.H{}をつけたら注意喚起がなくなったのでそのままにしました。

## Todo List

 - 上位者取得APIの実装

2024-11-18 11:33 UTC, oginoshikibu requested changes
言葉足らずですみません……！！
分からないことあったら聞いてください

2024-11-18 11:33 UTC, oginoshikibu commented on src/gamedate
このファイルは何でしょうか？おそらく不要だと思うので、削除お願いします！！

2024-11-18 11:33 UTC, oginoshikibu commented on src/ranking-table
こちらのファイルも不要だと思います！！！

2024-11-18 11:33 UTC, oginoshikibu commented on src/main.go
> +		db.ShowAllTableHeader(database) // development用
`func main()`直下（14行目）で既に実行済みなので、ここでの実行は不要です！
```suggestion
```

2024-11-18 11:33 UTC, oginoshikibu commented on src/main.go
> +		database.Create(&models.Result{ServiceID: 1, Score: 100, UserName: "user_7"})
この実装だと、POSTされると必ず{ServiceID: 1, Score: 100, UserName: "user_7"}を保存することになっています。
僕らが欲しい機能は、「POSTした内容を保存する」です！
練習課題2.1を参考に実装チャレンジしてみてください！！

2024-11-18 11:33 UTC, oginoshikibu commented on src/main.go
> +		c.JSON(http.StatusCreated, gin.H{})
返り値が201のみで空になっていますが、大体の201は「登録した内容をそのまま返す」ので、上記保存した内容を返すようにするとよいです！

2024-11-22 03:54 UTC, nekoyukichi commented on src/ranking-table
このファイルってどれのことですか...?

2024-11-22 03:54 UTC, nekoyukichi commented on src/main.go
> +		db.ShowAllTableHeader(database) // development用
消去しました

2024-11-22 03:54 UTC, nekoyukichi commented on src/main.go
> +		database.Create(&models.Result{ServiceID: 1, Score: 100, UserName: "user_7"})
POSTした内容を保存するように実装しました

2024-11-22 03:55 UTC, nekoyukichi commented on src/main.go
> +		c.JSON(http.StatusCreated, gin.H{})
保存した内容を返すように実装しました

2024-11-22 16:14 UTC, oginoshikibu approved these changes
LGTM

2024-11-22 16:15 UTC, merged